FROM python:3.9-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc libpq-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install --no-cache-dir "poetry>=2.1.3"

COPY pyproject.toml poetry.lock ./
COPY alembic.ini ./

RUN poetry config virtualenvs.create false \
 && poetry install --no-interaction --no-ansi --no-root

ENV PYTHONPATH=/app

EXPOSE 8000

CMD ["bash", "-c", "\
poetry run alembic upgrade head && \
poetry run python src/scripts/seed.py && \
uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload \
"]

