version: '3.8'

services:
  db:
    image: mysql:8.0.30
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=...
    volumes:
      - mysql_data:/var/lib/mysql
      # Файл инициализации базы, который создаст две базы: db1 и db2
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "3306:3306"

  backend:
    build: .
    container_name: backend_app
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  mysql_data:
