services:
  db:
    image: postgres:16-alpine
    env_file: .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    command: >
      /bin/bash -c "
      poetry run alembic upgrade head &&
      poetry run python -m scripts.seed
      "
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini

volumes:
  pgdata:
